
const fs = require('fs')
const SpotifyWebApi = require('spotify-web-api-node');
const token =  '' //Generated by authServer.js
const spotifyApi = new SpotifyWebApi();
spotifyApi.setAccessToken(token); 

searchTracks(); //searches tracks with random character


function searchTracks() {
    (async () => {
    
    console.log("searchTracks called")


    const randomOffset = Math.floor(Math.random() * 10000); //generate randomOffset

    const alphabet = "abcdefghijklmnopqrstuvwxyz"

    const randomCharacter = alphabet[Math.floor(Math.random() * alphabet.length)] //get a radom character to search tracks with


    const data = await spotifyApi.searchTracks(randomCharacter) 


    const firstPage = data.body.tracks.items;

    const max = 19

    const random = Math.floor(Math.random() * max)

    const artistID = await getRandArtist(randomCharacter) //get ID for random artist using randomCharacter a-z generated from above

    var genreSeed = seedGenres(); //get randomly seeded Genre


   recommend(firstPage[random].id,artistID,genreSeed) //pass trackSeed, TrackArtist, and genreSeed for recommend function


    })().catch(e => {
        console.error(e)
    });
}
    

function seedGenres() {
    (async () => {

    const data = await spotifyApi.getAvailableGenreSeeds()

    randSeed = Math.floor(Math.random() * (125 - 0 + 1) + 0) //126 genres so range is 0 - 125


    return data.body.genres[randSeed];


})().catch(e => {
    console.error(e);
});
}


function getRandArtist(randChar) {
    (async () => {
    console.log("getRandArtist called")
    const offsetArtist = Math.floor(Math.random() * (1000 - 0 + 1) + 0)

     const data = await spotifyApi.searchArtists(randChar, {limit: 1, offset: offsetArtist})

     console.log("data.body.artists.tiems[0].id is" + data.body.artists.items[0].id)
     
   

   return data.body.artists.items[0].id;
})().catch(e => {
    console.error(e);
});
}

function recommend(seedTrack,seedArtist,seedGenre) {
    (async () => {

    const data = await spotifyApi.getRecommendations({
        seed_artists: [seedArtist],
        seed_genres: [seedGenre],
        seed_tracks: [seedTrack],
        min_popularity: 40,
        limit: 30
        
    })
   
    const playList = await spotifyApi.createPlaylist("Completely Random", { "description": 'Your very own random playlist', 'public': true})
    

    console.log(JSON.stringify(data.body.tracks[0].uri))

    const playlistID = playList.body.id;

    const playlistAdd = []

    for( let i = 0; i < 30; i++) {
        const currTrackID = data.body.tracks[i].uri
        playlistAdd.push(currTrackID);

       // await spotifyApi.addTracksToPlaylist(playlistID, "spotify:track:"+currTrackID)
    }


    await spotifyApi.addTracksToPlaylist(playlistID,playlistAdd)


    console.log("Playlist Created!")

})().catch(e => {
    console.error(e);
});
}    

    

